# Generated by Django 4.0.5 on 2022-06-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
