# Generated by Django 4.0.5 on 2022-06-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0005_alter_customuser_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='movies_like',
            field=models.ManyToManyField(null=True, related_name='movies_like', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='movies_watched',
            field=models.ManyToManyField(null=True, related_name='movies_watched', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='movies_watchlist',
            field=models.ManyToManyField(null=True, related_name='movies_watchlist', to='movies.movie'),
        ),
        migrations.CreateModel(
            name='MovieScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='movies_rated',
            field=models.ManyToManyField(null=True, related_name='movies_rated', to='users.moviescore'),
        ),
    ]
