# Generated by Django 4.0.5 on 2022-11-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_movielog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movielog',
            name='watched_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
