# Generated by Django 4.0.5 on 2022-11-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_movielog_comment_alter_movielog_watched_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielog',
            old_name='reply_count',
            new_name='comment_count',
        ),
        migrations.AddField(
            model_name='movielog',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
