# Generated by Django 4.0.5 on 2022-11-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_reply_count_movielog_comment_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviescore',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='movies_like',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='movies_rated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='movies_watched',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='movies_watchlist',
        ),
        migrations.DeleteModel(
            name='MovieComment',
        ),
        migrations.DeleteModel(
            name='MovieScore',
        ),
    ]
