# Generated by Django 4.0.5 on 2022-11-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_moviescore_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='movies_average_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='movies_like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='movies_score_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='movies_watched_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='movies_watchlist_count',
            field=models.IntegerField(default=0),
        ),
    ]
