# Generated by Django 4.0.5 on 2022-06-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecrewmember',
            name='roles',
            field=models.ManyToManyField(blank=True, to='artists.occupation'),
        ),
    ]
