# Generated by Django 4.0.5 on 2022-06-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='movies.platformurl'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='productions',
            field=models.ManyToManyField(blank=True, to='movies.production'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='movies.tag'),
        ),
    ]
