# Generated by Django 4.0.5 on 2022-07-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_delete_moviecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
